language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: almilo@almilo.es
  api_key:
    secure: Cg5hJkpEwRpVUhWp7KFRHOpaXYfTftFzxAJ2ztUbw9RAjEkAh4kZdFA/Nej6xRRRq4zstLdYNOITb4Gww2TxMSECo+hgspGPkR22jjXzRJDZoxctGGx6Pu1HYwud6zkZNRCA/Yq8gYII53qzfL1dP3FJE7gm7t3vVI9m1zpqZcE=
  on:
    tags: true
before_install:
- npm install -g npm@latest
