language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: almilo@almilo.es
  api_key:
    secure: aerEMk7ka/I4PDo65SWlXojo9F3uyPnkStHp6GoH7EBrmyVO7/ITE17j1Ac4WDfnkZqDqHSrKK/OIkqKsiWr0pZjHog/fWZM8mnXgyQllKci1n+wsso7MBwvN+1YabcWWQA7P+8dGdmYhUw+KWomO/rB0Db/4+wUlGUCI0t2BEE=
  on:
    tags: true
    all_branches: true
